linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
  revive:
    package-comment: false

linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - gocognit
    - gocyclo
    - gofmt
    - misspell
    - nilerr
    - revive
    - staticcheck
    - whitespace

issues:
  exclude-use-default: false
  max-same-issues: 0
