linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  misspell:
    locale: US
  errcheck:
    check-type-assertions: false
    check-blank: false

linters:
  enable-all: false
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace

issues:
  exclude-use-default: false
  max-same-issues: 0
