on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  test:
    env:
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.32
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - uses: actions/checkout@v3
      - run: mysql -u$DB_USER -p$DB_PASSWORD -h$DB_HOST -P$DB_PORT $DB_NAME < ./deploy/mysql/schema.sql
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
