on:
  push:
    branches:
      - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - uses: actions/checkout@v3
      - run: go test ./... -coverprofile=coverage.coverage.out
      - name: report coverage
        uses: k1Low/octocov-actions@v0
